### ISSUE TITLE
Connection is not open in TransactionLockHandler (v1.19.12)

### ISSUE THREAD

**Issue by sergey-tihon** [hangfire-postgres/Hangfire.PostgreSql#282]
After the upgrade to the latest version (1.9.10) our Hangfire Dashboard died with an error

`53300: remaining connection slots are reserved for non-replication superuser connections

I am not 100% sure, but it looks like the issue is related to the `Hangfire.PostgreSql` dependencies upgrade from `1.9.9` to `1.9.10`. Everything works fine so far after rollback to `1.9.9`.

Update: dashboard also lost `Succeeded Jobs` and display 0.

Stack-trace is from the Hangfire Dashboard error and is most likely unrelated.
```
Npgsql.PostgresException:
   at Npgsql.Internal.NpgsqlConnector+<<ReadMessage>g__ReadMessageLong|226_0>d.MoveNext (Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.Internal.NpgsqlConnector+<<Open>g__OpenCore|208_1>d.MoveNext (Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.Internal.NpgsqlConnector+<Open>d__208.MoveNext (Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.PoolingDataSource+<OpenNewConnector>d__31.MoveNext (Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Threading.Tasks.ValueTask`1.get_Result (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.PoolingDataSource+<<Get>g__RentAsync|28_0>d.MoveNext (Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlConnection+<<Open>g__OpenAsync|45_0>d.MoveNext (Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlConnection.Open (Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection (Hangfire.PostgreSql, Version=1.9.10.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection (Hangfire.PostgreSql, Version=1.9.10.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.UseConnection (Hangfire.PostgreSql, Version=1.9.10.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetNumberOfJobsByStateName (Hangfire.PostgreSql, Version=1.9.10.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.SucceededListCount (Hangfire.PostgreSql, Version=1.9.10.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Dashboard.Pages.SucceededJobs.Execute (Hangfire.Core, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Dashboard.RazorPage.TransformText (Hangfire.Core, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Dashboard.RazorPage.ToString (Hangfire.Core, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch (Hangfire.Core, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware+<Invoke>d__5.MoveNext (Hangfire.AspNetCore, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware+<InvokeCore>d__4.MoveNext (Microsoft.AspNetCore.Http.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware+<<Invoke>g__AwaitRequestTask|6_0>d.MoveNext (Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware+<Invoke>d__5.MoveNext (NSwag.AspNetCore, Version=13.18.2.0, Culture=neutral, PublicKeyToken=c2d88086e098d109)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware+<Invoke>d__5.MoveNext (NSwag.AspNetCore, Version=13.18.2.0, Culture=neutral, PublicKeyToken=c2d88086e098d109)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware+<Invoke>d__10.MoveNext (NSwag.AspNetCore, Version=13.18.2.0, Culture=neutral, PublicKeyToken=c2d88086e098d109)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   
```

**Comment by azygis** [comment]
What happens if you use Npgsql 6 instead of 7? I'm not sure how well the support for v7 is at this time, considering Npgsql introduced data source while we still instantiate new connections in this library.

**Comment by sergey-tihon** [comment]
Sorry, it is hard to test on our solution. We fully migrated to v7 on Dec 2022 and everything worked fine till v1.9.10. 

We already use v7 features and some dependencies that already migrated to v7, so it is not easy to test on v6.

**Comment by azygis** [comment]
Hmmm, interesting. Nothing other than transaction scope issues have been changed in the last release, besides a few other small things not related to opening new/disposing of old connections.

Can you see whether it _is_ actually this library that's holding the connections? I don't know the full SQL magic to get the connection states, but at least pgAdmin shows active/idle connections. Setting application name in the Hangfire connection string would help distinguish whether the library is the real culprit.

What is your connection string? What is the registration of storage? Would love to get an F5-able reproduction since right now I'm really stumped. We've had a bunch of people here using external loadbalancers, hence disabling the internal Npgsql pooling, and a common denominator is exactly that.

**Comment by jakubkacorzyk** [comment]
Same issue here - after upgrading to `1.9.10`
```
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "value" POSITION: 59
at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult()
         at Dapper.SqlMapper.GridReader.NextResult() in /_/Dapper/SqlMapper.GridReader.cs:line 387
         at Dapper.SqlMapper.GridReader.ReadRow[T](Type type, Row row) in /_/Dapper/SqlMapper.GridReader.cs:line 196
         at Dapper.SqlMapper.GridReader.ReadSingle[T]() in /_/Dapper/SqlMapper.GridReader.cs:line 84
         at Hangfire.PostgreSql.PostgreSqlMonitoringApi.<GetStatistics>b__24_0(IDbConnection connection)
         at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
         at Hangfire.PostgreSql.PostgreSqlMonitoringApi.UseConnection[T](Func`2 func)
         at Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetStatistics()
         at Hangfire.Dashboard.RazorPage.<Assign>b__44_0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at Hangfire.Dashboard.RazorPage.get_Statistics()
         at Hangfire.Dashboard.Pages.HomePage.Execute()
         at Hangfire.Dashboard.RazorPage.TransformText(String body)
         at Hangfire.Dashboard.RazorPage.ToString()
         at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
         at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(Http
```

**Comment by azygis** [comment]
@jakubkacorzyk that is not the same issue. Column aliases have been fixed, new version just has to be pushed to NuGet by @frankhommers.

**Comment by davehutton** [comment]
big fan of hangfire and postgresql! This one clobbered me today. My output window spit out references to what jakubkacorzyk posted above but my browser said I had missing migrations which was a huge decoy. I spent so much time doing and re-doing my efcore migrations thinking I hosed something up or missed a procedure but I finally read my commit notes and noticed a nuget upgrade from 1.9.9 to 1.9.10 that did it. I'll hang with 1.9.9 until that gets hashed out. Just wanted to let others know

**Comment by pprometey** [comment]
Such a serious bug that breaks the normal operation of the application. The fix has been hanging for over a week now, but unfortunately the maintainer still hasn't bothered to release updates for Nuget. Facepalm

**Comment by pdevito3** [comment]
> @jakubkacorzyk that is not the same issue. Column aliases have been fixed, new version just has to be pushed to NuGet by @frankhommers.

I'm seeing the same issue after upgrading to `1.9.10` -- `1.9.9` is fine though. Also, seeing that's there's `1.19.11` on the github releases (that presumably fixes it), but i'm not seeing it on nuget as mentioned.

**Comment by azygis** [comment]
I believe this _might_ be fixed with #291. Won't close it until verified.

**Comment by azygis** [comment]
@jakubkacorzyk @davehutton @pdevito3 Sorry for the wait. The package has been pushed to NuGet. Let's keep this issue with OP's problem only now.

**Comment by azygis** [comment]
@sergey-tihon The new version has been pushed to the feed. Feel free to reopen the issue if you still experience these issues.

**Comment by azygis** [comment]
Please create a minimal runnable reproducible app. We're running the package at work with Npgsql 7.0 and have no issues with it, can't reproduce any of the issues you're describing.

**Comment by sergey-tihon** [comment]
And exception from Hangfire dashboard
```
Npgsql.NpgsqlException:
   at Npgsql.Internal.NpgsqlReadBuffer+<<Ensure>g__EnsureLong|42_0>d.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.Internal.NpgsqlConnector+<<ReadMessage>g__ReadMessageLong|233_0>d.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlDataReader+<NextResult>d__47.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlDataReader+<NextResult>d__47.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlDataReader.NextResult (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at Npgsql.NpgsqlCommand+<ExecuteReader>d__124.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlCommand+<ExecuteReader>d__124.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlCommand.ExecuteReader (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback (Dapper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /_/Dapper/SqlMapper.cs:1075)
   at Dapper.SqlMapper.QueryMultipleImpl (Dapper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /_/Dapper/SqlMapper.cs:1058)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.<GetStatistics>b__24_0 (Hangfire.PostgreSql, Version=1.19.11.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection (Hangfire.PostgreSql, Version=1.19.11.0, Culture=neutral, PublicKeyToken=null)
   at System.Lazy`1.ViaFactory (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Lazy`1.ExecutionAndPublication (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Lazy`1.CreateValue (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Hangfire.Dashboard.DashboardMetrics+<>c.<.cctor>b__1_0 (Hangfire.Core, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Dashboard.JsonStats+<Dispatch>d__0.MoveNext (Hangfire.Core, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware+<Invoke>d__5.MoveNext (Hangfire.AspNetCore, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
```

**Comment by azygis** [comment]
Sadly, neither this exception nor your initial post has the actual message.

**Comment by sergey-tihon** [comment]
What about this one? Or what we are looking for?

> 40P01: deadlock detected POSITION: 85 DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.

```
Npgsql.PostgresException:
   at Npgsql.Internal.NpgsqlConnector+<<ReadMessage>g__ReadMessageLong|233_0>d.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlDataReader+<NextResult>d__47.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlDataReader+<NextResult>d__47.MoveNext (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlDataReader.NextResult (Npgsql, Version=7.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at Dapper.SqlMapper+GridReader.NextResult (Dapper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /_/Dapper/SqlMapper.GridReader.cs:400)
   at Dapper.SqlMapper+GridReader.ReadRow (Dapper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /_/Dapper/SqlMapper.GridReader.cs:169)
   at Hangfire.PostgreSql.PostgreSqlMonitoringApi.<GetStatistics>b__24_0 (Hangfire.PostgreSql, Version=1.19.12.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection (Hangfire.PostgreSql, Version=1.19.12.0, Culture=neutral, PublicKeyToken=null)
   at System.Lazy`1.ViaFactory (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Lazy`1.ExecutionAndPublication (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Lazy`1.CreateValue (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Hangfire.Dashboard.DashboardMetrics+<>c.<.cctor>b__1_0 (Hangfire.Core, Version=1.7.33.0, Culture=neutral, PublicKeyToken=null)
```

**Comment by aamir0** [comment]
@sergey-tihon does the error appear at startup? I'm testing the latest version (1.19.12) and want to make sure there aren't any latent errors before deploying to other environments

**Comment by azygis** [comment]
I would still like to see error detail from postgresql with the exception. We have been using the latest version for quite a long time now and had no issues whatsoever.
