### ISSUE TITLE
Column "data" is of type jsonb but expression is of type text

### ISSUE THREAD

**Issue by JanmanX** [hangfire-postgres/Hangfire.PostgreSql#323]
Hi! 
After a recent upgrade of the `Hangfire.PostgreSql` package, I am starting to get the error:
```
MessageText: column "data" is of type jsonb but expression is of type text
```

It looks like a change introduced in version [1.19.13](https://github.com/hangfire-postgres/Hangfire.PostgreSql/compare/1.19.12...1.19.13#diff-087b53f4bc8c106ee8a3d30af37106024e6217b8200a54a2cd43bc0f774e9effR16). I checked that my Hangfire schema in PostgreSQL is indeed migrated to latest version 21, and the columns have the correct `jsonb` type. 

This happens during startup of the application, and the servers fail to start after that. Is this a bug, or an issue on my side?

Versions:
- Hangfire.PostgreSql 1.20.2
- Hangfire (.Core) 1.8.5
- .NET 7.0

Full stack trace:
```
POSITION: 208
at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlDataReader.NextResult()
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteNonQuery()
at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2848
at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 452
at Hangfire.PostgreSql.PostgreSqlConnection.<>c__DisplayClass18_0.<AnnounceServer>b__0(DbConnection connection)
at Hangfire.PostgreSql.PostgreSqlStorage.UseConnection[T](DbConnection dedicatedConnection, Func`2 func)
at Hangfire.PostgreSql.PostgreSqlConnection.AnnounceServer(String serverId, ServerContext context)
at Hangfire.Server.BackgroundServerProcess.CreateServer(BackgroundServerContext context)
at Hangfire.Server.BackgroundServerProcess.Execute(Guid executionId, BackgroundExecution execution, CancellationToken stoppingToken, CancellationToken stoppedToken, CancellationToken shutdownToken)
at Hangfire.Server.BackgroundProcessingServer.RunServer(Guid executionId, Object state)
at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
Exception data:
Severity: ERROR
SqlState: 42804
MessageText: column "data" is of type jsonb but expression is of type text
Hint: You will need to rewrite or cast the expression.
Position: 208
File: parse_target.c
Line: 587
Routine: transformAssignedExpr
```

**Comment by JanmanX** [comment]
This issue resolved itself after I rebuilt from the same commit today. Not sure what happened.

I'll keep this open for a few days in case someone has input on what happened :)

**Comment by azygis** [comment]
Sorry, it _seems_ like somehow an old version of was started while database was migrated by a newer version. That's the only thing I can think of.

**Comment by JanmanX** [comment]
@azygis That could explain it, as it might be possible this happened in my scenario. 
Thanks for following up on this :)

**Comment by azygis** [comment]
Reopening as the issue happens with the later versions. Need to investigate.

**Comment by azygis** [comment]
@brgrz can you give more details about this?

> Lately I observed the data type of the data column in server table changes from jsonb to text and back again

Does that happen at runtime or something?

**Comment by brgrz** [comment]
You were correct in saying that an old version of the app was started. The app containing the Hangfire server was still running of the previous versions of Hangfire nuget packages while one of the clients was upgraded to 1.8.x

**Comment by brgrz** [comment]
While I understand that schema updates are bound to happen two things I'd say about this:
- 1.7.x to 1.8.x shouldn't update schema in a breaking way, the server should be able to continue running of the old schema version,
- and, more importantly, applications where only the Hangfire client is installed shouldn't be updating schema, only the application with Hangfire server should be allowed to update schema.

**Comment by azygis** [comment]
Hangfire.Core update in itself did not have any schema changes, just to be clear. It just coincides with #298 which was released (probably) with the same version.

I'm afraid "not allowing clients to update schema" is for the consumer of the library to do by setting `PostgreSqlStorageOptions.PrepareSchemaIfNecessary`. Storage itself (which this library is) is not aware whether it's running in the server or client scenario.

I kinda agree with no-breaking-changes though. That was my bad assuming most of the usages are server and client in the same app. Came to the realization a bit later that it's not necessarily the case. Apologies.

The fix is straightforward though - match the versions in both apps. I can promise to try and not do the mistake of creating breaking changes without a new major release in the future.

P. S. my database was upgraded by another application as well, so it really seems like the inconsistency of versions. Closing this again.
