### ISSUE TITLE
NpgsqlDataSource support

### ISSUE THREAD

**Issue by maksimnarkevichdp** [hangfire-postgres/Hangfire.PostgreSql#355]
Good day,

Is there any plans for NpgsqDataSource support? https://www.npgsql.org/doc/release-notes/7.0.html#dbdatasource

I am eager to help if needed.

**Comment by azygis** [comment]
Out of the box - yes, it's kinda planned in my mind, but can't really do it quickly without quite some overhaul of how dependencies (namely Npgsql) are handled.

I think you should be able to do it yourself by using the bootstrapper overload that accepts `IConnectionFactory`. You can implement the factory any way you want, including supplying the connection from your data source. One way was discussed in #342.

**Comment by maksimnarkevichdp** [comment]
> Out of the box - yes, it's kinda planned in my mind, but can't really do it quickly without quite some overhaul of how dependencies (namely Npgsql) are handled.
> 
> I think you should be able to do it yourself by using the bootstrapper overload that accepts `IConnectionFactory`. You can implement the factory any way you want, including supplying the connection from your data source. One way was discussed in #342.

Thanks for the quick answer!

Can't find any info regarding what is the lifetime of IConnecitonFactory dependency?

**Comment by azygis** [comment]
It's not really a _dependency_ per se, it is not resolved from the dependency container. By default it just uses a `new NpgsqlConnectionFactory()` instance.

You should treat it as a singleton (similar to how `DbDataSource` typically should be).

**Comment by bweber** [comment]
Is there a recommended way to implement this. Here is what I have done:

```
public class ConnectionFactory(IServiceProvider serviceProvider) : IConnectionFactory
{
    public NpgsqlConnection GetOrCreateConnection() =>
        serviceProvider.GetRequiredService<NpgsqlDataSource>().CreateConnection();
}
```

Both ConnectionFactory and NpgsqlDataSource are registered as singletons:
`services.AddSingleton<IConnectionFactory, ConnectionFactory>();`

I am seeing a ton of connection exceptions in the logs:

```
Npgsql.NpgsqlException (0x80004005): The operation has timed out
 ---> System.TimeoutException: The operation has timed out.
   at Npgsql.ThrowHelper.ThrowNpgsqlExceptionWithInnerTimeoutException(String message)
   at Npgsql.Util.NpgsqlTimeout.Check()
   at Npgsql.Util.NpgsqlTimeout.CheckAndGetTimeLeft()
   at Npgsql.Util.NpgsqlTimeout.CheckAndApply(NpgsqlConnector connector)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection()
   at Hangfire.PostgreSql.PostgreSqlConnection.AcquireLock(String resource, TimeSpan timeout)
   at Hangfire.PostgreSql.PostgreSqlConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Server.RecurringJobScheduler.UseConnectionDistributedLock[T](JobStorage storage, Func`2 action) in C:\projects\hangfire-525\src\Hangfire.Core\Server\RecurringJobScheduler.cs:line 423
   at Hangfire.Server.RecurringJobScheduler.EnqueueNextRecurringJobs(BackgroundProcessContext context) in C:\projects\hangfire-525\src\Hangfire.Core\Server\RecurringJobScheduler.cs:line 203
   at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context) in C:\projects\hangfire-525\src\Hangfire.Core\Server\RecurringJobScheduler.cs:line 176
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state) in C:\projects\hangfire-525\src\Hangfire.Core\Server\BackgroundProcessDispatcherBuilder.cs:line 82
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state) in C:\projects\hangfire-525\src\Hangfire.Core\Processing\BackgroundExecution.cs:line 118
```

This seems to happen after a couple of minutes.
